name: Docker Build and Push

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours at minute 0 of each hour
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Fetch versions
      run: |
        IMAGE=${{ vars.UPSTREAM_IMAGE }}
        MY_IMAGE_NAME=${{ vars.MY_IMAGE_NAME }}
        # Get image info
        CURL_JSON=$(curl -s https://hub.docker.com/v2/repositories/$IMAGE/tags)

        # Query for digest of image "latest"
        LATEST_DIGEST=$( echo $CURL_JSON | jq -r '.results[] | select(.name == "latest") | .digest')
        echo "digest of latest: $LATEST_DIGEST"

        # versions as comma separated list
        # sed removed trailing comma
        VERSIONS_DOCKERHUB=$( echo $CURL_JSON | jq -r '.results[] | select(.digest == "'$LATEST_DIGEST'") | "'${MY_IMAGE_NAME}':" +  .name' | tr '\n' ',' | sed 's/,$//')
        echo "dockerhub versions with that digest: $VERSIONS_DOCKERHUB"

        VERSIONS_GITHUB=$( echo $CURL_JSON | jq -r '.results[] | select(.digest == "'$LATEST_DIGEST'") | "ghcr.io/'${MY_IMAGE_NAME}':" +  .name' | tr '\n' ',' | sed 's/,$//')
        echo "github versions with that digest: $VERSIONS_GITHUB"

        echo "LATEST_DIGEST=$LATEST_DIGEST" >> "$GITHUB_ENV"
        echo "VERSIONS_DOCKERHUB=$VERSIONS_DOCKERHUB" >> "$GITHUB_ENV"
        echo "VERSIONS_GITHUB=$VERSIONS_GITHUB" >> "$GITHUB_ENV"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: |
          IMAGE=${{ vars.UPSTREAM_IMAGE }}@${{ env.LATEST_DIGEST }}
        push: true
        tags: ${{ env.VERSIONS_DOCKERHUB }}

    - name: Notify about new build
      run: echo "Built and pushed version(s) ${{ env.VERSIONS_DOCKERHUB }} to Docker Hub from original image digest ${{ env.LATEST_DIGEST }}"



    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}
  
    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: |
          IMAGE=${{ vars.UPSTREAM_IMAGE }}@${{ env.LATEST_DIGEST }}
        push: true
        tags: ${{ env.VERSIONS_GITHUB }}
  
    - name: Notify about new build
      run: echo "Built and pushed version(s) ${{ env.VERSIONS_GITHUB }} to Docker Hub from original image digest ${{ env.LATEST_DIGEST }}"
  